### ISSUE TITLE
Using a better stock data API

### ISSUE THREAD

**Issue by tandrade96** [AlbertRtk/marketools#19]
The current data API is Stooq, and the site is in Polish. 

We may better use a more robust and documented API, [there are many free alternatives](https://towardsdatascience.com/best-5-free-stock-market-apis-in-2019-ad91dddec984)

**Comment by AlbertRtk** [comment]
Data are scrapped from the stooq.com. When I started a project that was a base for marketools it suited my needs better. I would prefer to focus on the development of analysis tool and stay with stooq at the moment. If needed, one can use yfinance as the source for data and still make use of analysis functions which should take OHLC dataframe as input.
